---
- name: Install Zookeeper Systemd service file
  template:
    src: zookeeper.systemd.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
  when: ansible_service_mgr == 'systemd'

- name: Install Zookeeper Upstart file
  template:
    src: zookeeper.upstart.service.j2
    dest: /etc/init/zookeeper.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart zookeeper
  when: ansible_service_mgr == 'upstart'

- name: Reload init scripts
  shell: |
    initctl reload-configuration
  when: upstart_init | changed
  notify:
    - restart zookeeper

- name: Setup zoo.cfg
  template:
    dest: "{{ zookeeper_conf_dir }}/zoo.cfg"
    src: zoo.cfg.j2
  notify:
    - restart zookeeper

- name: Setup myid
  template:
    dest: "{{ zookeeper_conf_dir }}/myid"
    src: myid.j2
  notify:
    - restart zookeeper

- name: Setup environment
  template:
    dest: "{{ zookeeper_conf_dir }}/environment"
    src: environment.j2
  notify:
    - restart zookeeper

- name: Setup log4j
  template:
    dest: "{{ zookeeper_conf_dir }}/log4j.properties"
    owner: root
    group: root
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart zookeeper

- meta: flush_handlers
