---
- name: Copy Zookeeper Systemd service file
  template:
    src: zookeeper.systemd.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
  when: init_service == 'systemd'

- name: Setup zoo.cfg
  template:
    dest: "{{zookeeper_conf_dir}}/zoo.cfg"
    src: zoo.cfg.j2
  notify:
    - restart zookeeper

- name: Setup myid
  template:
    dest: "{{zookeeper_conf_dir}}/myid"
    src: myid.j2
  notify:
    - restart zookeeper

- name: Setup environment
  template:
    dest: "{{zookeeper_conf_dir}}/environment"
    src: environment.j2
  notify:
    - restart zookeeper

- name: Setup log4j
  template:
    dest: "{{zookeeper_conf_dir}}/log4j.properties"
    owner: root
    group: root
    mode: 644
    src: log4j.properties.j2
  notify:
    - restart zookeeper

- meta: flush_handlers
