---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Install OpenJDK
  apt: name=openjdk-7-jre-headless state=present

- name: Install Zookeeper
  apt: name=zookeeperd state=present
