---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Enable and start zookeeper
  service: name=zookeeper state=started enabled=yes

- name: wait for zookeeper port
  wait_for: port={{zookeeper_client_port}} state=started timeout={{ monasca_wait_for_period }}
