---
- name: restart zookeeper
  service:
    name: zookeeper
    state: restarted

#- name: Reload systemd
#  systemd:
#    daemon_reload: yes
#  when: init_service == 'systemd'

- name: Reload systemd
  command: systemctl daemon-reload

