---

- name: Reload upstart
  command: initctl reload-configuration

- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart zookeeper
  service:
    name: zookeeper
    state: restarted

